CREATE TABLE test_model(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	age INT (11) NOT NULL DEFAULT -1 COMMENT 'age',
	user_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'userName',
	created_at DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'createdAt',
	updated_at DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'updatedAt',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'test_model';